TWITTER_CONSUMER_KEY: xxxxxxx
TWITTER_CONSUMER_SECRET: xxxxxxx
TWITTER_ACCESS_TOKEN: xxxxxxx
TWITTER_ACCESS_TOKEN_SECRET: xxxxxxx

TUMBLR_CLIENT_ID: xxxxxxx
TUMBLR_CLIENT_SECRET: xxxxxxx
TUMBLR_ACCESS_TOKEN: xxxxxxx
TUMBLR_ACCESS_TOKEN_SECRET: xxxxxxx
